/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_s;
//import static Restaurant_s.ItemsCost.itemsCostofM;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.awt.Component;
import java.util.Date;


/**
 *
 * @author cess_skkrt
 */
public class Restaurants extends javax.swing.JFrame {

    double Tax_Rate = 206.39; 
 
    double[] items = new double[13];
    
    double iTax, iTotal, iSubtotal, iCost;

   public class itemsC{
       
        double GrilledFish;
        double ChickenEgg;
        double ChickenSheesh;
        double GrilledSalmon;
    
        double Coffee;
        double Tea;
        double MineralWater;
        double Soju;
        double Coke;
    
        double FreenFries;
        double VanillaIceCream;
        double CheeseSandwich;
        double CheeseBurger;
           
        double itemsCost1;
        double itemsCost2;
        double itemsCost3;
        double itemsCost;
        
    public double GetItems(){
            
            itemsCost1 = GrilledFish + ChickenEgg + ChickenSheesh + GrilledSalmon;
            itemsCost2 = Coffee + Tea + MineralWater + Soju + Coke;
            itemsCost3 = FreenFries + VanillaIceCream + CheeseSandwich + CheeseBurger;
            itemsCost = itemsCost1 + itemsCost2 + itemsCost3;
            return(itemsCost);
   }
        
        double PriceGrilledFish = 150;
        double PriceChickenEgg = 140;
        double PriceChickenSheesh = 200;
        double PriceGrilledSalmon = 150;
        double PriceCoffee = 100;
        double PriceTea = 30;
        double PriceMineralWater = 20;
        double PriceSoju = 60;
        double PriceCoke = 30;
        double PriceFreenFries = 60;
        double PriceVanillaIceCream = 20;
        double PriceCheeseSandwich = 40;
        double PriceCheeseBurger = 50;
       
   }
    /**
     * Creates new form Restaurants
     */
    public Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jChkGrilledFish = new javax.swing.JCheckBox();
        jChkChickenEgg = new javax.swing.JCheckBox();
        jChkChickenSheesh = new javax.swing.JCheckBox();
        jChkGrilledSalmon = new javax.swing.JCheckBox();
        jtxtChickenEgg = new javax.swing.JTextField();
        jtxtGrilledFish = new javax.swing.JTextField();
        jtxtChickenSheesh = new javax.swing.JTextField();
        jtxtGrilledSalmon = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jChkCoffee = new javax.swing.JCheckBox();
        jChkTea = new javax.swing.JCheckBox();
        jChkMineralWater = new javax.swing.JCheckBox();
        jChkSoju = new javax.swing.JCheckBox();
        jChkCoke = new javax.swing.JCheckBox();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtTea = new javax.swing.JTextField();
        jtxtMineralWater = new javax.swing.JTextField();
        jtxtSoju = new javax.swing.JTextField();
        jtxtCoke = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        jChkFreenFries = new javax.swing.JCheckBox();
        jChkVanillaIceCream = new javax.swing.JCheckBox();
        jChkCheeseSandwich = new javax.swing.JCheckBox();
        jChkCheeseBurger = new javax.swing.JCheckBox();
        jtxtVanillaIceCream = new javax.swing.JTextField();
        jtxtCheeseSandwich = new javax.swing.JTextField();
        jtxtCheeseBurger = new javax.swing.JTextField();
        jtxtFreenFries = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jlblSubTotal = new javax.swing.JTextField();
        jlblTax = new javax.swing.JTextField();
        jlblTotal = new javax.swing.JTextField();
        CostOfDrinks = new javax.swing.JTextField();
        CostOfMeal = new javax.swing.JTextField();
        CostOfDesserts = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.lightGray);
        setPreferredSize(new java.awt.Dimension(1370, 700));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBox.highlight"));

        jTextField2.setBackground(java.awt.Color.lightGray);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setText("MEAL");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jChkGrilledFish.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkGrilledFish.setText("Grilled Fish and Sweet Potato");
        jChkGrilledFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkGrilledFishActionPerformed(evt);
            }
        });

        jChkChickenEgg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkChickenEgg.setText("Chicken Egg and Rice");
        jChkChickenEgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkChickenEggActionPerformed(evt);
            }
        });

        jChkChickenSheesh.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkChickenSheesh.setText("Chicken sheesh kalalabs");
        jChkChickenSheesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkChickenSheeshActionPerformed(evt);
            }
        });

        jChkGrilledSalmon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkGrilledSalmon.setText("Grilled salmon w/ D'Sauce");
        jChkGrilledSalmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkGrilledSalmonActionPerformed(evt);
            }
        });

        jtxtChickenEgg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenEgg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenEgg.setText("0");
        jtxtChickenEgg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jtxtChickenEgg.setEnabled(false);
        jtxtChickenEgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenEggActionPerformed(evt);
            }
        });
        jtxtChickenEgg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChickenEggKeyTyped(evt);
            }
        });

        jtxtGrilledFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtGrilledFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtGrilledFish.setText("0");
        jtxtGrilledFish.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jtxtGrilledFish.setEnabled(false);
        jtxtGrilledFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGrilledFishActionPerformed(evt);
            }
        });
        jtxtGrilledFish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtGrilledFishKeyTyped(evt);
            }
        });

        jtxtChickenSheesh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenSheesh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenSheesh.setText("0");
        jtxtChickenSheesh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jtxtChickenSheesh.setEnabled(false);
        jtxtChickenSheesh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChickenSheeshKeyTyped(evt);
            }
        });

        jtxtGrilledSalmon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtGrilledSalmon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtGrilledSalmon.setText("0");
        jtxtGrilledSalmon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jtxtGrilledSalmon.setEnabled(false);
        jtxtGrilledSalmon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtGrilledSalmonKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChkGrilledSalmon)
                            .addComponent(jChkChickenSheesh)
                            .addComponent(jChkChickenEgg)
                            .addComponent(jChkGrilledFish))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtGrilledFish, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtGrilledSalmon, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtChickenEgg, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtChickenSheesh, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkGrilledFish)
                    .addComponent(jtxtGrilledFish, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkChickenEgg)
                    .addComponent(jtxtChickenEgg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkChickenSheesh)
                    .addComponent(jtxtChickenSheesh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtGrilledSalmon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkGrilledSalmon))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Receipt", jPanel7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));

        jTextField7.setBackground(java.awt.Color.lightGray);
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField7.setText("DRINKS");

        jChkCoffee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkCoffee.setText("Coffee");
        jChkCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCoffeeActionPerformed(evt);
            }
        });

        jChkTea.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkTea.setText("Tea");
        jChkTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkTeaActionPerformed(evt);
            }
        });

        jChkMineralWater.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkMineralWater.setText("Mineral Water");
        jChkMineralWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkMineralWaterActionPerformed(evt);
            }
        });

        jChkSoju.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkSoju.setText("Soju");
        jChkSoju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkSojuActionPerformed(evt);
            }
        });

        jChkCoke.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkCoke.setText("Coke");
        jChkCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCokeActionPerformed(evt);
            }
        });

        jtxtCoffee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setText("0");
        jtxtCoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtxtCoffee.setEnabled(false);
        jtxtCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCoffeeActionPerformed(evt);
            }
        });
        jtxtCoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCoffeeKeyTyped(evt);
            }
        });

        jtxtTea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTea.setText("0");
        jtxtTea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtxtTea.setEnabled(false);
        jtxtTea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTeaKeyTyped(evt);
            }
        });

        jtxtMineralWater.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMineralWater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMineralWater.setText("0");
        jtxtMineralWater.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtxtMineralWater.setEnabled(false);
        jtxtMineralWater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMineralWaterKeyTyped(evt);
            }
        });

        jtxtSoju.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSoju.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSoju.setText("0");
        jtxtSoju.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtxtSoju.setEnabled(false);
        jtxtSoju.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSojuKeyTyped(evt);
            }
        });

        jtxtCoke.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCoke.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoke.setText("0");
        jtxtCoke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtxtCoke.setEnabled(false);
        jtxtCoke.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCokeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChkCoffee)
                            .addComponent(jChkSoju)
                            .addComponent(jChkCoke)
                            .addComponent(jChkTea)
                            .addComponent(jChkMineralWater))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMineralWater, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSoju, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCoke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jChkCoffee)
                        .addGap(21, 21, 21)
                        .addComponent(jChkTea)
                        .addGap(18, 18, 18)
                        .addComponent(jChkMineralWater)
                        .addGap(18, 18, 18)
                        .addComponent(jChkSoju)
                        .addGap(24, 24, 24)
                        .addComponent(jChkCoke)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jtxtTea, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtMineralWater, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtSoju, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtCoke, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(240, 240, 240));

        jTextField13.setBackground(java.awt.Color.lightGray);
        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField13.setText("DESSERTS");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jChkFreenFries.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkFreenFries.setText("Freen Fries");
        jChkFreenFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkFreenFriesActionPerformed(evt);
            }
        });

        jChkVanillaIceCream.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkVanillaIceCream.setText("Vanilla Ice Cream");
        jChkVanillaIceCream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkVanillaIceCreamActionPerformed(evt);
            }
        });

        jChkCheeseSandwich.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkCheeseSandwich.setText("Cheese Sandwich");
        jChkCheeseSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCheeseSandwichActionPerformed(evt);
            }
        });

        jChkCheeseBurger.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jChkCheeseBurger.setText("Cheese Burger");
        jChkCheeseBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCheeseBurgerActionPerformed(evt);
            }
        });

        jtxtVanillaIceCream.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanillaIceCream.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanillaIceCream.setText("0");
        jtxtVanillaIceCream.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtxtVanillaIceCream.setEnabled(false);
        jtxtVanillaIceCream.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtVanillaIceCreamKeyTyped(evt);
            }
        });

        jtxtCheeseSandwich.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCheeseSandwich.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCheeseSandwich.setText("0");
        jtxtCheeseSandwich.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtxtCheeseSandwich.setEnabled(false);
        jtxtCheeseSandwich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCheeseSandwichKeyTyped(evt);
            }
        });

        jtxtCheeseBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCheeseBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCheeseBurger.setText("0");
        jtxtCheeseBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtxtCheeseBurger.setEnabled(false);
        jtxtCheeseBurger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCheeseBurgerKeyTyped(evt);
            }
        });

        jtxtFreenFries.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFreenFries.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFreenFries.setText("0");
        jtxtFreenFries.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jtxtFreenFries.setEnabled(false);
        jtxtFreenFries.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFreenFriesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jChkFreenFries)
                                .addComponent(jChkVanillaIceCream))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jChkCheeseBurger)
                                .addComponent(jChkCheeseSandwich)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtxtFreenFries, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtCheeseSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jtxtVanillaIceCream, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jChkFreenFries)
                    .addComponent(jtxtFreenFries, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkVanillaIceCream)
                    .addComponent(jtxtVanillaIceCream, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCheeseSandwich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkCheeseSandwich))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkCheeseBurger)
                    .addComponent(jtxtCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jPanel5.setEnabled(false);

        jTextField18.setBackground(new java.awt.Color(240, 240, 240));
        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField18.setText("Cost of Meal");
        jTextField18.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField18.setCaretColor(new java.awt.Color(204, 204, 204));

        jTextField19.setBackground(new java.awt.Color(240, 240, 240));
        jTextField19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField19.setText("Cost of Desserts");
        jTextField19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField20.setBackground(new java.awt.Color(240, 240, 240));
        jTextField20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField20.setText("Cost of Drinks");
        jTextField20.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField21.setBackground(new java.awt.Color(240, 240, 240));
        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField21.setText("Sub Total:");
        jTextField21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField22.setBackground(new java.awt.Color(240, 240, 240));
        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField22.setText("Tax:");
        jTextField22.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField23.setBackground(new java.awt.Color(240, 240, 240));
        jTextField23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField23.setText("Total:");
        jTextField23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jlblSubTotal.setEnabled(false);

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jlblTax.setEnabled(false);

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jlblTotal.setEnabled(false);

        CostOfDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CostOfDrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CostOfDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        CostOfDrinks.setEnabled(false);

        CostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CostOfMeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CostOfMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        CostOfMeal.setEnabled(false);
        CostOfMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostOfMealActionPerformed(evt);
            }
        });

        CostOfDesserts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CostOfDesserts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CostOfDesserts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        CostOfDesserts.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CostOfMeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CostOfDesserts, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlblTax)
                                .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(44, 44, 44))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(CostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CostOfDesserts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(CostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));

        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button1.setLabel("TOTAL");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button2.setLabel("RESET");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        button3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button3.setLabel("EXIT");
        button3.setMaximumSize(new java.awt.Dimension(32770, 32770));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button4.setLabel("RECEIPT / UPDATE");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField1.setEditable(false);
        jTextField1.setBackground(java.awt.Color.lightGray);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Restaurant Management System");
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jtxtGrilledFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGrilledFishActionPerformed
        // ito yung textbox ng grilledfish kung saan dito ilalagay yung quantity
    }//GEN-LAST:event_jtxtGrilledFishActionPerformed

    private void jChkTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkTeaActionPerformed
        // mag hahighlight pag nag lagay ka ng number
        if (jChkTea.isSelected()){
            jtxtTea.setEnabled(true);
            jtxtTea.requestFocus();
            jtxtTea.setText("");
        }
        else{
            jtxtTea.setEnabled(false);
            jtxtTea.setText("0");
        }
    }//GEN-LAST:event_jChkTeaActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed
        
    private void jtxtChickenEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenEggActionPerformed
        // ito yung textbox ng Chicken egg kung saan dito ilalagay yung quantity
    }//GEN-LAST:event_jtxtChickenEggActionPerformed

    private void jChkMineralWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkMineralWaterActionPerformed
         // mag hahighlight pag nag lagay ka ng number
        if (jChkMineralWater.isSelected()){
            jtxtMineralWater.setEnabled(true);
            jtxtMineralWater.requestFocus();
            jtxtMineralWater.setText("");
            
        }
        else{
            jtxtMineralWater.setEnabled(false);
            jtxtMineralWater.setText("0");
        }
    }//GEN-LAST:event_jChkMineralWaterActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here: Total
        
        itemsC itemCostofM = new itemsC();
       
        itemCostofM.GrilledFish = itemCostofM.PriceGrilledFish * Double.parseDouble(jtxtGrilledFish.getText());
        itemCostofM.ChickenEgg = itemCostofM.PriceChickenEgg * Double.parseDouble(jtxtChickenEgg.getText());
        itemCostofM.ChickenSheesh = itemCostofM.PriceChickenSheesh * Double.parseDouble(jtxtChickenSheesh.getText());
        itemCostofM.GrilledSalmon = itemCostofM.PriceGrilledSalmon * Double.parseDouble(jtxtGrilledSalmon.getText());
        
        itemCostofM.Coffee = itemCostofM.PriceCoffee * Double.parseDouble(jtxtCoffee.getText());
        itemCostofM.Tea = itemCostofM.PriceTea* Double.parseDouble(jtxtTea.getText());
        itemCostofM.MineralWater = itemCostofM.PriceMineralWater * Double.parseDouble(jtxtMineralWater.getText());
        itemCostofM.Soju = itemCostofM.PriceSoju * Double.parseDouble(jtxtSoju.getText());
        itemCostofM.Coke = itemCostofM.PriceCoke * Double.parseDouble(jtxtCoke.getText());
        
        itemCostofM.FreenFries = itemCostofM.PriceFreenFries * Double.parseDouble(jtxtFreenFries.getText());
        itemCostofM.VanillaIceCream= itemCostofM.PriceVanillaIceCream * Double.parseDouble(jtxtVanillaIceCream.getText());
        itemCostofM.CheeseSandwich = itemCostofM.PriceCheeseSandwich * Double.parseDouble(jtxtCheeseSandwich.getText());
        itemCostofM.CheeseBurger = itemCostofM.PriceCheeseBurger * Double.parseDouble(jtxtCheeseBurger.getText());
        
        items[0] = Double.parseDouble(jtxtGrilledFish.getText());
        items[1] = Double.parseDouble(jtxtChickenEgg.getText());
        items[2] = Double.parseDouble(jtxtChickenSheesh.getText());
        items[3] = Double.parseDouble(jtxtGrilledSalmon.getText());
        items[4] = Double.parseDouble(jtxtCoffee.getText());
        items[5] = Double.parseDouble(jtxtTea.getText());
        items[6] = Double.parseDouble(jtxtMineralWater.getText());
        items[7] = Double.parseDouble(jtxtSoju.getText());
        items[8] = Double.parseDouble(jtxtCoke.getText());
        items[9] = Double.parseDouble(jtxtFreenFries.getText());
        items[10] = Double.parseDouble(jtxtVanillaIceCream.getText());
        items[11] = Double.parseDouble(jtxtCheeseSandwich.getText());
        items[12] = Double.parseDouble(jtxtCheeseBurger.getText());
        
        iSubtotal = items[0] + items[1] +items[2] + items[3] + items[4] + items[5] + items[6] + 
                items[7] + items[8] + items[9] + items[10] + items[11] + items[12];
        
        iCost = itemCostofM.GetItems();
     
        iTax = (iSubtotal * Tax_Rate)/100;
       
        String pMeal = String.format("%.2f", itemCostofM.itemsCost1);
        CostOfMeal.setText(pMeal);
        
        String pDrinks = String.format("%.2f", itemCostofM.itemsCost2);
        CostOfDrinks.setText(pDrinks);
        
        String pDesserts = String.format("%.2f", itemCostofM.itemsCost3);
        CostOfDesserts.setText(pDesserts);
        
        String cTax = String.format("%.2f",iTax);
        jlblTax.setText(cTax);
        
        String cSubtotal = String.format("%.2f",iSubtotal);
        jlblSubTotal.setText(cSubtotal);
        
        String itotal = String.format("%.2f",iSubtotal + iTax + iCost);
        jlblTotal.setText(itotal);
        
        if (jlblSubTotal.isShowing()){
            jlblSubTotal.setEnabled(true); 
        }
        else{
            jlblSubTotal.setEnabled(false);
        }
        
         if (jlblTax.isShowing()){
            jlblTax.setEnabled(true); 
        }
        else{
            jlblTax.setEnabled(false);
        }
         
          if (jlblTotal.isShowing()){
            jlblTotal.setEnabled(true); 
        }
        else{
            jlblTotal.setEnabled(false);
        }
        
        
        if (CostOfMeal.isShowing()){
            CostOfMeal.setEnabled(true); 
        }
        else{
            CostOfMeal.setEnabled(false);
        }
        
        if (CostOfDesserts.isShowing()){
            CostOfDesserts.setEnabled(true); 
        }
        else{
            CostOfDesserts.setEnabled(false);
        }
        
        if (CostOfDrinks.isShowing()){
            CostOfDrinks.setEnabled(true); 
        }
        else{
            CostOfDrinks.setEnabled(false);
        }
        
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        jtxtChickenEgg.setText("0");
        jtxtGrilledFish.setText("0");
        jtxtGrilledSalmon.setText("0");
        jtxtChickenSheesh.setText("0");
        jtxtCoffee.setText("0");
        jtxtTea.setText("0");
        jtxtMineralWater.setText("0");
        jtxtSoju.setText("0");
        jtxtCoke.setText("0");
        jtxtFreenFries.setText("0");
        jtxtVanillaIceCream.setText("0");
        jtxtCheeseSandwich.setText("0");
        jtxtCheeseBurger.setText("0");
        
        jtxtChickenEgg.setEnabled(false);
        jtxtGrilledFish.setEnabled(false);
        jtxtGrilledSalmon.setEnabled(false);
        jtxtChickenSheesh.setEnabled(false);
        jtxtCoffee.setEnabled(false);
        jtxtTea.setEnabled(false);
        jtxtMineralWater.setEnabled(false);
        jtxtSoju.setEnabled(false);
        jtxtCoke.setEnabled(false);
        jtxtFreenFries.setEnabled(false);
        jtxtVanillaIceCream.setEnabled(false);
        jtxtCheeseSandwich.setEnabled(false);
        jtxtCheeseBurger.setEnabled(false);
        
        jTextArea1.setEnabled(false);
        jTextArea1.setText(null);
        
        CostOfMeal.setText(null);
        CostOfDesserts.setText(null);
        CostOfDrinks.setText(null);
        
        CostOfMeal.setEnabled(false);
        CostOfDesserts.setEnabled(false);
        CostOfDrinks.setEnabled(false);
        
        jlblTax.setText(null);
        jlblSubTotal.setText(null);
        jlblTotal.setText(null);
        
        jlblTax.setEnabled(false);
        jlblSubTotal.setEnabled(false);
        jlblTotal.setEnabled(false);
        
        jChkGrilledFish.setSelected(false);
        jChkChickenEgg.setSelected(false);
        jChkChickenSheesh.setSelected(false);
        jChkGrilledSalmon.setSelected(false);
        jChkCoffee.setSelected(false);
        jChkTea.setSelected(false);
        jChkMineralWater.setSelected(false);
        jChkSoju.setSelected(false);
        jChkCoke.setSelected(false);
        jChkFreenFries.setSelected(false);
        jChkVanillaIceCream.setSelected(false);
        jChkCheeseSandwich.setSelected(false);
        jChkCheeseBurger.setSelected(false);
        
    }//GEN-LAST:event_ResetActionPerformed

private JFrame frame;
    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here: EXIT
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Restaurant Management", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void jtxtGrilledFishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtGrilledFishKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtGrilledFishKeyTyped

    private void jtxtChickenEggKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChickenEggKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtChickenEggKeyTyped

    private void jtxtChickenSheeshKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChickenSheeshKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtChickenSheeshKeyTyped

    private void jtxtGrilledSalmonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtGrilledSalmonKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtGrilledSalmonKeyTyped

    private void jtxtCoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCoffeeKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtCoffeeKeyTyped

    private void jtxtTeaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTeaKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtTeaKeyTyped

    private void jtxtMineralWaterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMineralWaterKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtMineralWaterKeyTyped

    private void jtxtSojuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSojuKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtSojuKeyTyped

    private void jtxtCokeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCokeKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtCokeKeyTyped

    private void jtxtFreenFriesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFreenFriesKeyTyped
         // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtFreenFriesKeyTyped

    private void jtxtVanillaIceCreamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtVanillaIceCreamKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtVanillaIceCreamKeyTyped

    private void jtxtCheeseSandwichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCheeseSandwichKeyTyped
        // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtCheeseSandwichKeyTyped

    private void jtxtCheeseBurgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCheeseBurgerKeyTyped
         // TODO add your handling code here: hindi matatype yung String pang numbers lang
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtCheeseBurgerKeyTyped

    private void jChkChickenEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkChickenEggActionPerformed
        // mag hahighlight pag nag lagay ka ng number
        if (jChkChickenEgg.isSelected()){
            jtxtChickenEgg.setEnabled(true);
            jtxtChickenEgg.requestFocus();
            jtxtChickenEgg.setText("");
        }
        else{
            jtxtChickenEgg.setEnabled(false);
            jtxtChickenEgg.setText("0");
        }
    }//GEN-LAST:event_jChkChickenEggActionPerformed

    private void jChkChickenSheeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkChickenSheeshActionPerformed
       // mag hahighlight pag nag lagay ka ng number
        if (jChkChickenSheesh.isSelected()){
            jtxtChickenSheesh.setEnabled(true);
            jtxtChickenSheesh.requestFocus();
            jtxtChickenSheesh.setText("");
        }
        else{
            jtxtChickenSheesh.setEnabled(false);
            jtxtChickenSheesh.setText("0");
        }
    }//GEN-LAST:event_jChkChickenSheeshActionPerformed

    private void jChkGrilledSalmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkGrilledSalmonActionPerformed
        // mag hahighlight pag nag lagay ka ng number
        if (jChkGrilledSalmon.isSelected()){
            jtxtGrilledSalmon.setEnabled(true);
            jtxtGrilledSalmon.requestFocus();
            jtxtGrilledSalmon.setText("");
        }
        else{
            jtxtGrilledSalmon.setEnabled(false);
            jtxtGrilledSalmon.setText("0");
        }
    }//GEN-LAST:event_jChkGrilledSalmonActionPerformed

    private void jChkCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCoffeeActionPerformed
         // mag hahighlight pag nag lagay ka ng number
        if (jChkCoffee.isSelected()){
            jtxtCoffee.setEnabled(true);
            jtxtCoffee.requestFocus();
            jtxtCoffee.setText("");
        }
        else{
            jtxtCoffee.setEnabled(false);
            jtxtCoffee.setText("0");
        }
    }//GEN-LAST:event_jChkCoffeeActionPerformed

    private void jChkSojuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkSojuActionPerformed
         // mag hahighlight pag nag lagay ka ng number
        if (jChkSoju.isSelected()){
            jtxtSoju.setEnabled(true);
            jtxtSoju.requestFocus();
            jtxtSoju.setText("");
        }
        else{
            jtxtSoju.setEnabled(false);
            jtxtSoju.setText("0");
        }
    }//GEN-LAST:event_jChkSojuActionPerformed

    private void jChkCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCokeActionPerformed
        // mag hahighlight pag nag lagay ka ng number
        if (jChkCoke.isSelected()){
            jtxtCoke.setEnabled(true);
            jtxtCoke.requestFocus();
            jtxtCoke.setText("");
        }
        else{
            jtxtCoke.setEnabled(false);
            jtxtCoke.setText("0");
        }
    }//GEN-LAST:event_jChkCokeActionPerformed

    private void jChkFreenFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkFreenFriesActionPerformed
         // mag hahighlight pag nag lagay ka ng number
        if (jChkFreenFries.isSelected()){
            jtxtFreenFries.setEnabled(true);
            jtxtFreenFries.requestFocus();
            jtxtFreenFries.setText("");
        }
        else{
            jtxtFreenFries.setEnabled(false);
             jtxtFreenFries.setText("0");
        }
    }//GEN-LAST:event_jChkFreenFriesActionPerformed

    private void jChkVanillaIceCreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkVanillaIceCreamActionPerformed
         // mag hahighlight pag nag lagay ka ng number
        if (jChkVanillaIceCream.isSelected()){
            jtxtVanillaIceCream.setEnabled(true);
            jtxtVanillaIceCream.requestFocus();
            jtxtVanillaIceCream.setText("");
        }
        else{
            jtxtVanillaIceCream.setEnabled(false);
            jtxtVanillaIceCream.setText("0");
        }
    }//GEN-LAST:event_jChkVanillaIceCreamActionPerformed

    private void jChkCheeseSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCheeseSandwichActionPerformed
       // mag hahighlight pag nag lagay ka ng number
        if (jChkCheeseSandwich.isSelected()){
            jtxtCheeseSandwich.setEnabled(true);
            jtxtCheeseSandwich.requestFocus();
            jtxtCheeseSandwich.setText("");
        }
        else{
            jtxtCheeseSandwich.setEnabled(false);
            jtxtCheeseSandwich.setText("0");
        }
    }//GEN-LAST:event_jChkCheeseSandwichActionPerformed

    private void jChkCheeseBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCheeseBurgerActionPerformed
        // mag hahighlight pag nag lagay ka ng number
        if (jChkCheeseBurger.isSelected()){
            jtxtCheeseBurger.setEnabled(true);
            jtxtCheeseBurger.requestFocus();
            jtxtCheeseBurger.setText("");
        }
        else{
            jtxtCheeseBurger.setEnabled(false);
            jtxtCheeseBurger.setText("0");
        }
    }//GEN-LAST:event_jChkCheeseBurgerActionPerformed

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
        // TODO add your handling code here:
       Date date = new Date();
       String dt = date.toString();
       
       jTextArea1.setText("***************************************************");
       jTextArea1.setText(jTextArea1.getText() + "\t\n\t                WELCOME TO ");
       jTextArea1.setText(jTextArea1.getText() + "\t\n\t        RESTAURANT MANAGEMENT SYSTEM ");
       jTextArea1.setText(jTextArea1.getText() + "\t\n\t        PROK T3 LOVESKIRT STREET ");
       jTextArea1.setText(jTextArea1.getText() + "\t\n\t          www.LoveSkirt@.com");
       jTextArea1.setText(jTextArea1.getText() + "\t\n\t              +69987654321");
       jTextArea1.setText(jTextArea1.getText() + "\n\t        " + dt);
      
       jTextArea1.setText(jTextArea1.getText() + "\t\n************************************************** ");
       
       jTextArea1.setText(jTextArea1.getText() + "\t\n");
       jTextArea1.setText(jTextArea1.getText() + "\t\n Item Name ");
       jTextArea1.setText(jTextArea1.getText() + "\t\t\t   Qty ");
       jTextArea1.setText(jTextArea1.getText() + "\t   Unit Price ");
       jTextArea1.setText(jTextArea1.getText() + "\t\n-----------------------------------------------------");
       
       if (jChkGrilledFish.isSelected()){
            jTextArea1.append("\n " + jChkGrilledFish.getText());
            jTextArea1.append("\t    " + jtxtGrilledFish.getText());
            jTextArea1.append("\t      " + "150");
            jTextArea1.setEnabled(true);
        }
       if (jChkChickenEgg.isSelected()){
            jTextArea1.append("\n " + jChkChickenEgg.getText());
            jTextArea1.append("\t\t    " + jtxtChickenEgg.getText());
            jTextArea1.append("\t      " + "140");
            jTextArea1.setEnabled(true);
        }
       if (jChkChickenSheesh.isSelected()){
            jTextArea1.append("\n " + jChkChickenSheesh.getText());
            jTextArea1.append("\t    " + jtxtChickenSheesh.getText());
            jTextArea1.append("\t      " + "200");
            jTextArea1.setEnabled(true);
        }
        if (jChkGrilledSalmon.isSelected()){
            jTextArea1.append("\n " + jChkGrilledSalmon.getText());
            jTextArea1.append("\t    " + jtxtGrilledSalmon.getText());
            jTextArea1.append("\t      " + "150");
            jTextArea1.setEnabled(true);
        }
        
        //Drinks
        if (jChkCoffee.isSelected()){
            jTextArea1.append("\n " + jChkCoffee.getText());
            jTextArea1.append("\t\t\t\t    " + jtxtCoffee.getText());
            jTextArea1.append("\t      " + "100");
            jTextArea1.setEnabled(true);
        }
        if (jChkTea.isSelected()){
            jTextArea1.append("\n " + jChkTea.getText());
            jTextArea1.append("\t\t\t\t    " + jtxtTea.getText());
            jTextArea1.append("\t       " + "30");
            jTextArea1.setEnabled(true);
        }
          if (jChkMineralWater.isSelected()){
            jTextArea1.append("\n " + jChkMineralWater.getText());
            jTextArea1.append("\t\t\t    " + jtxtMineralWater.getText());
            jTextArea1.append("\t       " + "20");
            jTextArea1.setEnabled(true);
        }
           if (jChkSoju.isSelected()){
            jTextArea1.append("\n " + jChkSoju.getText());
            jTextArea1.append("\t\t\t\t    " + jtxtSoju.getText());
            jTextArea1.append("\t       " + "60");
            jTextArea1.setEnabled(true);
        }
           if (jChkCoke.isSelected()){
            jTextArea1.append("\n " + jChkCoke.getText());
            jTextArea1.append("\t\t\t\t    " + jtxtCoke.getText());
            jTextArea1.append("\t       " + "30");
            jTextArea1.setEnabled(true);
        }
           
           //Desserts
        if (jChkFreenFries.isSelected()){
            jTextArea1.append("\n " + jChkFreenFries.getText());
            jTextArea1.append("\t\t\t    " + jtxtFreenFries.getText());
            jTextArea1.append("\t       " + "60");
            jTextArea1.setEnabled(true);
        }
        if (jChkVanillaIceCream.isSelected()){
            jTextArea1.append("\n " + jChkVanillaIceCream.getText());
            jTextArea1.append("\t\t    " + jtxtVanillaIceCream.getText());
            jTextArea1.append("\t       " + "20");
            jTextArea1.setEnabled(true);
        }
        if (jChkCheeseSandwich.isSelected()){
            jTextArea1.append("\n " + jChkCheeseSandwich.getText());
            jTextArea1.append("\t\t    " + jtxtCheeseSandwich.getText());
            jTextArea1.append("\t       " + "40");
            jTextArea1.setEnabled(true);
        }
        if (jChkCheeseBurger.isSelected()){
            jTextArea1.append("\n " + jChkCheeseBurger.getText());
            jTextArea1.append("\t\t\t    " + jtxtCheeseBurger.getText());
            jTextArea1.append("\t       " + "50");
            jTextArea1.setEnabled(true);
        }
        
        jTextArea1.setText(jTextArea1.getText() + "\t\n---------------------------------------------------- ");
        jTextArea1.setText(jTextArea1.getText() + "\t\n Cost of Meal:" + "\t\t\t\t    " + CostOfMeal.getText());
        jTextArea1.setText(jTextArea1.getText() + "\t\n Cost of Deserts:" + "\t\t\t    " + CostOfDesserts.getText());
        jTextArea1.setText(jTextArea1.getText() + "\t\n Cost of Drinks:" + "\t\t\t    " + CostOfDrinks.getText());
        jTextArea1.setText(jTextArea1.getText() + "\t\n---------------------------------------------------- ");
        
        jTextArea1.setText(jTextArea1.getText() + "\t\n Sub Total:" + "\t\t\t\t    " + jlblSubTotal.getText());
        jTextArea1.setText(jTextArea1.getText() + "\t\n Tax:" + "\t\t\t\t\t    " + jlblTax.getText());
        jTextArea1.setText(jTextArea1.getText() + "\t\n Total:" + "\t\t\t\t\t    " + jlblTotal.getText());
        jTextArea1.setText(jTextArea1.getText() + "\t\n---------------------------------------------------- ");
        
       
        jTextArea1.setText(jTextArea1.getText() + "\t\n\t            HAVE A NICE DAY     ");
        jTextArea1.setText(jTextArea1.getText() + "\t\n\t         THANK YOU & COME AGAIN ");

        jTextArea1.setText(jTextArea1.getText() + "\t\n************************************************** ");
        
        
    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jChkGrilledFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkGrilledFishActionPerformed
         if (jChkGrilledFish.isSelected()){
             jtxtGrilledFish.setEnabled(true);
             jtxtGrilledFish.requestFocus();
             jtxtGrilledFish.setText("");
        }
        else{
            jtxtGrilledFish.setEnabled(false);
            jtxtGrilledFish.setText("0");
        }
    }//GEN-LAST:event_jChkGrilledFishActionPerformed

    private void CostOfMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostOfMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostOfMealActionPerformed

    private void jtxtCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCoffeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CostOfDesserts;
    private javax.swing.JTextField CostOfDrinks;
    private javax.swing.JTextField CostOfMeal;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private javax.swing.JCheckBox jChkCheeseBurger;
    private javax.swing.JCheckBox jChkCheeseSandwich;
    private javax.swing.JCheckBox jChkChickenEgg;
    private javax.swing.JCheckBox jChkChickenSheesh;
    private javax.swing.JCheckBox jChkCoffee;
    private javax.swing.JCheckBox jChkCoke;
    private javax.swing.JCheckBox jChkFreenFries;
    private javax.swing.JCheckBox jChkGrilledFish;
    private javax.swing.JCheckBox jChkGrilledSalmon;
    private javax.swing.JCheckBox jChkMineralWater;
    private javax.swing.JCheckBox jChkSoju;
    private javax.swing.JCheckBox jChkTea;
    private javax.swing.JCheckBox jChkVanillaIceCream;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jlblSubTotal;
    private javax.swing.JTextField jlblTax;
    private javax.swing.JTextField jlblTotal;
    private javax.swing.JTextField jtxtCheeseBurger;
    private javax.swing.JTextField jtxtCheeseSandwich;
    private javax.swing.JTextField jtxtChickenEgg;
    private javax.swing.JTextField jtxtChickenSheesh;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtCoke;
    private javax.swing.JTextField jtxtFreenFries;
    private javax.swing.JTextField jtxtGrilledFish;
    private javax.swing.JTextField jtxtGrilledSalmon;
    private javax.swing.JTextField jtxtMineralWater;
    private javax.swing.JTextField jtxtSoju;
    private javax.swing.JTextField jtxtTea;
    private javax.swing.JTextField jtxtVanillaIceCream;
    // End of variables declaration//GEN-END:variables

}
